name: Pre-commit Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Cache Python virtual environment
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ hashFiles('uv.lock') }}

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install project dependencies for pyright check
        if: steps.cache-venv.outputs.cache-hit != 'true'
        env:
          UV_PROJECT_ENVIRONMENT: venv
        run: |
          pip install uv
          uv sync --extra pre-commit

      - name: Run pre-commit hooks
        run: |
          source venv/bin/activate
          pre-commit run --all-files
